//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AeEntities : DbContext
    {
        public AeEntities()
            : base("name=AeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Aeropuerto> Aeropuertoes { get; set; }
        public virtual DbSet<Asiento> Asientoes { get; set; }
        public virtual DbSet<Avion> Avions { get; set; }
        public virtual DbSet<Cliente> Clientes { get; set; }
        public virtual DbSet<Localidad> Localidads { get; set; }
        public virtual DbSet<Pai> Pais { get; set; }
        public virtual DbSet<Reserva> Reservas { get; set; }
        public virtual DbSet<TarjetaEmbarque> TarjetaEmbarques { get; set; }
        public virtual DbSet<Vuelo> Vueloes { get; set; }
    }
}
