//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asiento
    {
        public int Id_asiento { get; set; }
        public Nullable<int> Id_Avion { get; set; }
        public Nullable<int> Fila { get; set; }
        public Nullable<int> Columna { get; set; }
        public string Planta { get; set; }
    
        public virtual Avion Avion { get; set; }
    }
}
