//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reserva
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Reserva()
        {
            this.TarjetaEmbarques = new HashSet<TarjetaEmbarque>();
        }
    
        public int Id_reserva { get; set; }
        public Nullable<int> Id_vuelo { get; set; }
        public Nullable<int> Asientos { get; set; }
        public Nullable<int> Id_cliente { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Vuelo Vuelo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TarjetaEmbarque> TarjetaEmbarques { get; set; }
    }
}
