//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class TarjetaEmbarque
    {
        public int Id_tarjetaEmbarque { get; set; }
        public Nullable<int> Id_Reserva { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<int> Id_cliente { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Reserva Reserva { get; set; }
    }
}
