//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class TarjetaEmbarque
    {
        public int Id_tarjetaEmbarque { get; set; }
        public Nullable<int> Id_Reserva { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<int> Id_cliente { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Reserva Reserva { get; set; }
    }
}
